apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    control-plane: daemon
  name: kruise-daemon-linux
  namespace: kruise-system
spec:
  selector:
    matchLabels:
      control-plane: daemon
  template:
    metadata:
      labels:
        control-plane: daemon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      containers:
      - args:
        - --logtostderr=true
        - --v=5
        - --addr=:10221
        - --feature-gates=ImagePullJobGate=true
        - --socket-file=
        - --enable-pprof=true
        - --pprof-addr=localhost:10222
        command:
        - /kruise-daemon
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CONTAINERD_ADDRESS
          value: /hostvarrun/containerd/containerd.sock
        image: openkruise/kruise-manager:v1.7.2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10221
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: daemon
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: "0"
            memory: "0"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /hostvarrun
          name: runtime-socket
          readOnly: true
        - name: tmp
          mountPath: /tmp
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kruise-daemon
      serviceAccountName: kruise-daemon
      terminationGracePeriodSeconds: 10
      tolerations:
      - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - hostPath:
          path: /var/run
          type: ""
        name: runtime-socket
      - name: tmp
        hostPath:
          path: /tmp
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 10%
    type: RollingUpdate
