apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    control-plane: daemon
  name: linux-idle
  namespace: kruise-system
spec:
  selector:
    matchLabels:
      control-plane: daemon
  template:
    metadata:
      labels:
        control-plane: daemon
    spec:
      containers:
      - command: [ "sleep", "3600" ]
        image: busybox
        imagePullPolicy: Always
        name: daemon
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: "0"
            memory: "0"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /hostvarrun
          name: runtime-socket
          readOnly: true
        - name: tmp
          mountPath: /tmp
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kruise-daemon
      serviceAccountName: kruise-daemon
      terminationGracePeriodSeconds: 10
      tolerations:
      - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - hostPath:
          path: /var/run
          type: ""
        name: runtime-socket
      - name: tmp
        hostPath:
          path: /tmp
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 10%
    type: RollingUpdate
