/*
Copyright 2020 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package configuration

import (
	"bytes"
	"context"
	"fmt"
	"net/url"
	"sort"

	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	"k8s.io/apimachinery/pkg/api/equality"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	clientset "k8s.io/client-go/kubernetes"
	"k8s.io/klog/v2"

	"github.com/openkruise/kruise/pkg/features"
	utilfeature "github.com/openkruise/kruise/pkg/util/feature"
	"github.com/openkruise/kruise/pkg/webhook/types"
	webhookutil "github.com/openkruise/kruise/pkg/webhook/util"
)

const (
	mutatingWebhookConfigurationName   = "kruise-mutating-webhook-configuration"
	validatingWebhookConfigurationName = "kruise-validating-webhook-configuration"
)

func Ensure(kubeClient clientset.Interface, handlers map[string]types.HandlerGetter, caBundle []byte) error {
	mutatingConfig, err := kubeClient.AdmissionregistrationV1().MutatingWebhookConfigurations().Get(context.TODO(), mutatingWebhookConfigurationName, metav1.GetOptions{})
	if err != nil {
		return fmt.Errorf("not found MutatingWebhookConfiguration %s", mutatingWebhookConfigurationName)
	}
	validatingConfig, err := kubeClient.AdmissionregistrationV1().ValidatingWebhookConfigurations().Get(context.TODO(), validatingWebhookConfigurationName, metav1.GetOptions{})
	if err != nil {
		return fmt.Errorf("not found ValidatingWebhookConfiguration %s", validatingWebhookConfigurationName)
	}

	if utilfeature.DefaultFeatureGate.Enabled(features.EnableExternalCerts) {
		// if using external certs, only check the caBundle of webhook
		for _, wh := range mutatingConfig.Webhooks {
			path, err := getPath(&wh.ClientConfig)
			if err != nil {
				return err
			}
			if _, ok := handlers[path]; !ok {
				klog.Warningf("Ignore webhook for %s in configuration", path)
				continue
			}
			if !bytes.Equal(wh.ClientConfig.CABundle, caBundle) {
				return fmt.Errorf("caBundle of MutatingWebhookConfiguration %s does not match the external caBundle", mutatingWebhookConfigurationName)
			}
		}

		for _, wh := range validatingConfig.Webhooks {
			path, err := getPath(&wh.ClientConfig)
			if err != nil {
				return err
			}
			if _, ok := handlers[path]; !ok {
				klog.Warningf("Ignore webhook for %s in configuration", path)
				continue
			}
			if !bytes.Equal(wh.ClientConfig.CABundle, caBundle) {
				return fmt.Errorf("caBundle of ValidatingWebhookConfiguration %s does not match the external caBundle", validatingWebhookConfigurationName)
			}
		}
		return nil
	}

	// if using certs generated by kruise, update webhook configurations
	// Work directly with the live webhooks from etcd, preserving any fields
	// (like NamespaceSelector) that cloud providers may have added.
	oldMutatingConfig := mutatingConfig.DeepCopy()
	oldValidatingConfig := validatingConfig.DeepCopy()

	// Clean up legacy template annotation if present
	delete(mutatingConfig.Annotations, "template")
	delete(validatingConfig.Annotations, "template")

	var mutatingWHs []admissionregistrationv1.MutatingWebhook
	for i := range mutatingConfig.Webhooks {
		wh := &mutatingConfig.Webhooks[i]
		path, err := getPath(&wh.ClientConfig)
		if err != nil {
			return err
		}
		if _, ok := handlers[path]; !ok {
			klog.InfoS("Ignore webhook in configuration", "path", path)
			continue
		}

		wh.ClientConfig.CABundle = caBundle
		if wh.ClientConfig.Service != nil {
			wh.ClientConfig.Service.Namespace = webhookutil.GetNamespace()
			wh.ClientConfig.Service.Name = webhookutil.GetServiceName()

			if host := webhookutil.GetHost(); len(host) > 0 {
				convertClientConfig(&wh.ClientConfig, host, webhookutil.GetPort())
			}
		}

		mutatingWHs = append(mutatingWHs, *wh)
	}
	mutatingConfig.Webhooks = mutatingWHs

	var validatingWHs []admissionregistrationv1.ValidatingWebhook
	for i := range validatingConfig.Webhooks {
		wh := &validatingConfig.Webhooks[i]
		path, err := getPath(&wh.ClientConfig)
		if err != nil {
			return err
		}
		if _, ok := handlers[path]; !ok {
			klog.InfoS("Ignore webhook in configuration", "path", path)
			continue
		}

		wh.ClientConfig.CABundle = caBundle
		if wh.ClientConfig.Service != nil {
			wh.ClientConfig.Service.Namespace = webhookutil.GetNamespace()
			wh.ClientConfig.Service.Name = webhookutil.GetServiceName()

			if host := webhookutil.GetHost(); len(host) > 0 {
				convertClientConfig(&wh.ClientConfig, host, webhookutil.GetPort())
			}
		}

		validatingWHs = append(validatingWHs, *wh)
	}
	validatingConfig.Webhooks = validatingWHs

	if !AreSemanticEqualMutatingWebhooks(mutatingConfig, oldMutatingConfig) {
		klog.V(3).InfoS("MutatingWebhookConfiguration has changes, updating",
			"config", mutatingConfig.Name, "webhooks", len(mutatingConfig.Webhooks))
		if _, err := kubeClient.AdmissionregistrationV1().MutatingWebhookConfigurations().Update(context.TODO(), mutatingConfig, metav1.UpdateOptions{}); err != nil {
			return fmt.Errorf("failed to update %s: %v", mutatingWebhookConfigurationName, err)
		}
		klog.InfoS("Update caBundle success", "MutatingWebhookConfigurations", klog.KObj(mutatingConfig))
	} else {
		klog.V(4).InfoS("MutatingWebhookConfiguration is semantically equal, skipping update",
			"config", mutatingConfig.Name)
	}

	if !AreSemanticEqualValidatingWebhooks(validatingConfig, oldValidatingConfig) {
		klog.V(3).InfoS("ValidatingWebhookConfiguration has changes, updating",
			"config", validatingConfig.Name, "webhooks", len(validatingConfig.Webhooks))
		if _, err := kubeClient.AdmissionregistrationV1().ValidatingWebhookConfigurations().Update(context.TODO(), validatingConfig, metav1.UpdateOptions{}); err != nil {
			return fmt.Errorf("failed to update %s: %v", validatingWebhookConfigurationName, err)
		}
		klog.InfoS("Update caBundle success", "ValidatingWebhookConfigurations", klog.KObj(validatingConfig))
	} else {
		klog.V(4).InfoS("ValidatingWebhookConfiguration is semantically equal, skipping update",
			"config", validatingConfig.Name)
	}

	return nil
}

// AreSemanticEqualMutatingWebhooks compares two MutatingWebhookConfigurations using semantic equality.
// It returns true if the configurations are semantically equal, even if the order of webhooks
// or MatchExpressions differs. This avoids unnecessary updates when only ordering changes.
func AreSemanticEqualMutatingWebhooks(config1, config2 *admissionregistrationv1.MutatingWebhookConfiguration) bool {
	normalized1 := normalizeMutatingWebhookConfiguration(config1)
	normalized2 := normalizeMutatingWebhookConfiguration(config2)
	return equality.Semantic.DeepEqual(normalized1, normalized2)
}

// AreSemanticEqualValidatingWebhooks compares two ValidatingWebhookConfigurations using semantic equality.
// It returns true if the configurations are semantically equal, even if the order of webhooks
// or MatchExpressions differs. This avoids unnecessary updates when only ordering changes.
func AreSemanticEqualValidatingWebhooks(config1, config2 *admissionregistrationv1.ValidatingWebhookConfiguration) bool {
	normalized1 := normalizeValidatingWebhookConfiguration(config1)
	normalized2 := normalizeValidatingWebhookConfiguration(config2)
	return equality.Semantic.DeepEqual(normalized1, normalized2)
}

// normalizeMutatingWebhookConfiguration returns a normalized copy of the configuration
// with webhooks sorted by name and MatchExpressions sorted by key.
func normalizeMutatingWebhookConfiguration(config *admissionregistrationv1.MutatingWebhookConfiguration) *admissionregistrationv1.MutatingWebhookConfiguration {
	if config == nil {
		return nil
	}
	normalized := config.DeepCopy()

	// Sort webhooks by name
	sort.Slice(normalized.Webhooks, func(i, j int) bool {
		return normalized.Webhooks[i].Name < normalized.Webhooks[j].Name
	})

	// Sort MatchExpressions within each webhook's NamespaceSelector
	for i := range normalized.Webhooks {
		normalizeNamespaceSelector(normalized.Webhooks[i].NamespaceSelector)
	}

	return normalized
}

// normalizeValidatingWebhookConfiguration returns a normalized copy of the configuration
// with webhooks sorted by name and MatchExpressions sorted by key.
func normalizeValidatingWebhookConfiguration(config *admissionregistrationv1.ValidatingWebhookConfiguration) *admissionregistrationv1.ValidatingWebhookConfiguration {
	if config == nil {
		return nil
	}
	normalized := config.DeepCopy()

	// Sort webhooks by name
	sort.Slice(normalized.Webhooks, func(i, j int) bool {
		return normalized.Webhooks[i].Name < normalized.Webhooks[j].Name
	})

	// Sort MatchExpressions within each webhook's NamespaceSelector
	for i := range normalized.Webhooks {
		normalizeNamespaceSelector(normalized.Webhooks[i].NamespaceSelector)
	}

	return normalized
}

// normalizeNamespaceSelector normalizes a LabelSelector to ensure consistent comparison:
//   - Sorts MatchExpressions by key to handle ordering differences
//   - MatchLabels (map) is already order-independent and equality.Semantic.DeepEqual
//     handles nil vs empty map correctly, so we don't need to normalize it
func normalizeNamespaceSelector(selector *metav1.LabelSelector) {
	if selector == nil {
		return
	}

	// Sort MatchExpressions by key
	if len(selector.MatchExpressions) > 0 {
		sort.Slice(selector.MatchExpressions, func(i, j int) bool {
			return selector.MatchExpressions[i].Key < selector.MatchExpressions[j].Key
		})
	}
}

func getPath(clientConfig *admissionregistrationv1.WebhookClientConfig) (string, error) {
	if clientConfig.Service != nil {
		return *clientConfig.Service.Path, nil
	}
	if clientConfig.URL != nil {
		u, err := url.Parse(*clientConfig.URL)
		if err != nil {
			return "", err
		}
		return u.Path, nil
	}
	return "", fmt.Errorf("invalid clientConfig: %+v", clientConfig)
}

func convertClientConfig(clientConfig *admissionregistrationv1.WebhookClientConfig, host string, port int) {
	url := fmt.Sprintf("https://%s:%d%s", host, port, *clientConfig.Service.Path)
	clientConfig.URL = &url
	clientConfig.Service = nil
}
