apiVersion: apps.kruise.io/v1alpha1
kind: ContainerRecreateRequest
metadata:
  namespace: kruise-system
  name: ws2022-idle-cmlgj-v1
spec:
  podName: ws2022-idle-cmlgj
  containers:
  # list of container name that need to be recreated, at least one
  - name: daemon
  strategy:
    failurePolicy: Fail # or 'Ignore'. If 'Fail', the CRR will abort when one container failed to stop or recreate
    orderedRecreate: false # 'true' indicates to recreate the next container only if the previous one has recreated completely
    terminationGracePeriodSeconds: 30 # optional duration in seconds to wait the container terminating gracefully
    unreadyGracePeriodSeconds: 3 # duration for the Pod is marked as not ready before its preStop hook is executed and it is stopped
    minStartedSeconds: 10 # the new container will be consider as Succeeded only if it has started over minStartedSeconds
  activeDeadlineSeconds: 300 # the CRR will be marked as Completed immediately if it has ran over deadline duration since created
  ttlSecondsAfterFinished: 1800 # the time CRR remain as completed before the CRR is deleted
