apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    control-plane: daemon
  name: ws2022-idle
  namespace: kruise-system
spec:
  selector:
    matchLabels:
      control-plane: daemon
  template:
    metadata:
      labels:
        control-plane: daemon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      containers:
      - command:
        - powershell.exe
        - -Command
        - Write-Host "Sleep for 36000 seconds"
        - Start-Sleep -Seconds 36000
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: mcr.microsoft.com/windows/servercore:ltsc2022
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10221
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: daemon
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: "0"
            memory: "0"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: containerd-volume
          mountPath: "C:\\Program Files\\containerd"
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kruise-daemon
      serviceAccountName: kruise-daemon
      terminationGracePeriodSeconds: 10
      tolerations:
      - operator: Exists
      nodeSelector:
        kubernetes.io/os: windows
        kubernetes.azure.com/os-sku: Windows2022
      volumes:
      - name: containerd-volume
        hostPath:
          path: "C:\\Program Files\\containerd"
          type: Directory
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 10%
    type: RollingUpdate
